name: Gitのグラフの更新

on:
  workflow_call:
    inputs:
      cache-key:
        description: キャッシュのキー
        default: "0"
        type: string
      git-graph-ref:
        description: 使用するgit-bahn/git-graphのref
        default: 5ae210fa9f2cc59e4f51c9b40a98ea0fce5fa040
        type: string
      max-count:
        description: グラフに表示するコミットの数
        default: 20
        type: number
      branch-name:
        description: グラフの画像を置くブランチ
        default: git-graph
        type: string
      commit-msg:
        description: コミットメッセージ
        default: Gitのグラフを更新
        type: string
      commit-name:
        description: コミットの作成者のユーザー名
        default: github-actions[bot]
        type: string
      commit-email:
        description: コミットの作成者のメールアドレス
        default: 41898282+github-actions[bot]@users.noreply.github.com
        type: string
      commit-date:
        description: コミットの日付
        default: Thu Jan 1 00:00:00 1970 +0000
        type: string

permissions:
  contents: write

jobs:
  git-graph:
    name: Gitのグラフの更新
    runs-on: ubuntu-latest
    steps:
      - id: cache
        uses: actions/cache/restore@v5
        with:
          path: git-graph/target/release
          key: ${{ inputs.cache-key }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v7
        with:
          repository: git-bahn/git-graph
          ref: ${{ inputs.git-graph-ref }}
          path: git-graph
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: cargo build --manifest-path git-graph/Cargo.toml --release
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: git-graph/target/release
          key: ${{ inputs.cache-key }}
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          path: data
      - run: |
          ../git-graph/target/release/git-graph --svg -n ${{ inputs.max-count }} > git-graph.svg
          git checkout --orphan '${{ inputs.branch-name }}'
          git rm -rf .
          sed -i '1a<style>path[fill="#00000030"]{fill:#ffffff30}svg{background:#0d1117}text{fill:#fff}</style>' git-graph.svg
          git add .
          git config user.name '${{ inputs.commit-name }}'
          git config user.email '${{ inputs.commit-email }}'
          git commit --date="$GIT_COMMITTER_DATE" -m '${{ inputs.commit-msg }}'
          git push -f origin '${{ inputs.branch-name }}'
        working-directory: data
        env:
          GIT_COMMITTER_DATE: ${{ inputs.commit-date }}
